### ISSUE TITLE
Angular Js Alt yapısının hazırlanması

### ISSUE THREAD

**Issue by gok2689** [RemmDevelop/RemmWiki#7]
-Projeye entegre edilmesi.
-Controller ların hazırlanması

**Comment by SevcanAlkan** [comment]
{"id":"1","name":"LEAN","data":{"lang":"TR-tr","docs":{"id":"1","subject":"Genel",  "content":"Boş JSON data gelicek...","parentId":"","createDate":"",    "updateDate":"","docVersion":"0.0.1"}},"img": "","helpVersion":"2.0.1","isVisible":true}
